NAME = $(notdir $(CURDIR))

CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++20

SRCS =	main.cpp \
		Harl.cpp

OBJS = $(SRCS:.cpp=.o)

RM = rm -f

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJS)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all